//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HappyDo.ApplicationService.AutoMapperSettings.Settings {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.9.0.0")]
    internal sealed partial class AutoMapperExtension : global::System.Configuration.ApplicationSettingsBase {
        
        private static AutoMapperExtension defaultInstance = ((AutoMapperExtension)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new AutoMapperExtension())));
        
        public static AutoMapperExtension Default {
            get {
                return defaultInstance;
            }
        }
    }
}
